# Generated by Django 4.2.13 on 2024-11-11 16:14

from django.db import migrations, models
import factura_config.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("factura_config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_width", models.FloatField(default=21, help_text="Ancho en cm")),
                (
                    "page_height",
                    models.FloatField(default=29.7, help_text="Alto en cm"),
                ),
                (
                    "margin_top",
                    models.FloatField(default=1, help_text="Margen superior en cm"),
                ),
                (
                    "margin_bottom",
                    models.FloatField(default=1, help_text="Margen inferior en cm"),
                ),
                (
                    "margin_left",
                    models.FloatField(default=1, help_text="Margen izquierdo en cm"),
                ),
                (
                    "margin_right",
                    models.FloatField(default=1, help_text="Margen derecho en cm"),
                ),
                (
                    "header_font",
                    models.CharField(
                        choices=[
                            ("Helvetica", "Helvetica"),
                            ("Times-Roman", "Times Roman"),
                            ("Courier", "Courier"),
                        ],
                        default="Helvetica",
                        help_text="Fuente para encabezados",
                        max_length=50,
                    ),
                ),
                (
                    "content_font",
                    models.CharField(
                        choices=[
                            ("Helvetica", "Helvetica"),
                            ("Times-Roman", "Times Roman"),
                            ("Courier", "Courier"),
                        ],
                        default="Helvetica",
                        help_text="Fuente para contenido",
                        max_length=50,
                    ),
                ),
                (
                    "custom_font",
                    models.FileField(
                        blank=True,
                        help_text="Archivo de fuente personalizada (.ttf o .otf)",
                        null=True,
                        upload_to="fonts/",
                        validators=[factura_config.models.validate_font_file],
                    ),
                ),
                (
                    "font_size_header",
                    models.IntegerField(
                        default=12, help_text="Tamaño de fuente para encabezados"
                    ),
                ),
                (
                    "font_size_content",
                    models.IntegerField(
                        default=10, help_text="Tamaño de fuente para contenido"
                    ),
                ),
                (
                    "font_size_total",
                    models.IntegerField(
                        default=12, help_text="Tamaño de fuente para totales"
                    ),
                ),
                (
                    "header_color",
                    models.CharField(
                        choices=[
                            ("black", "Negro"),
                            ("blue", "Azul"),
                            ("red", "Rojo"),
                            ("green", "Verde"),
                            ("gray", "Gris"),
                        ],
                        default="black",
                        help_text="Color para encabezados",
                        max_length=20,
                    ),
                ),
                (
                    "content_color",
                    models.CharField(
                        choices=[
                            ("black", "Negro"),
                            ("blue", "Azul"),
                            ("red", "Rojo"),
                            ("green", "Verde"),
                            ("gray", "Gris"),
                        ],
                        default="black",
                        help_text="Color para contenido",
                        max_length=20,
                    ),
                ),
                (
                    "table_border_color",
                    models.CharField(
                        choices=[
                            ("black", "Negro"),
                            ("blue", "Azul"),
                            ("red", "Rojo"),
                            ("green", "Verde"),
                            ("gray", "Gris"),
                        ],
                        default="black",
                        help_text="Color del borde de las tablas",
                        max_length=20,
                    ),
                ),
                (
                    "table_border_width",
                    models.FloatField(
                        default=1, help_text="Grosor del borde de las tablas en puntos"
                    ),
                ),
                (
                    "column_width_article",
                    models.FloatField(
                        default=8, help_text="Ancho columna artículo en cm"
                    ),
                ),
                (
                    "column_width_quantity",
                    models.FloatField(
                        default=2, help_text="Ancho columna cantidad en cm"
                    ),
                ),
                (
                    "column_width_price",
                    models.FloatField(
                        default=3, help_text="Ancho columna precio en cm"
                    ),
                ),
                (
                    "column_width_total",
                    models.FloatField(default=3, help_text="Ancho columna total en cm"),
                ),
            ],
            options={
                "verbose_name": "Configuración Factura",
                "verbose_name_plural": "Configuración Factura",
            },
        ),
    ]
