# Generated by Django 4.2.13 on 2024-11-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("factura_config", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facturaconfiguration",
            name="custom_font",
        ),
        migrations.RemoveField(
            model_name="facturaconfiguration",
            name="page_height",
        ),
        migrations.AlterField(
            model_name="facturaconfiguration",
            name="column_width_article",
            field=models.FloatField(
                default=4, help_text="Ancho columna artículo en cm"
            ),
        ),
        migrations.AlterField(
            model_name="facturaconfiguration",
            name="column_width_price",
            field=models.FloatField(
                default=1.5, help_text="Ancho columna precio en cm"
            ),
        ),
        migrations.AlterField(
            model_name="facturaconfiguration",
            name="column_width_quantity",
            field=models.FloatField(
                default=1, help_text="Ancho columna cantidad en cm"
            ),
        ),
        migrations.AlterField(
            model_name="facturaconfiguration",
            name="column_width_total",
            field=models.FloatField(default=1.5, help_text="Ancho columna total en cm"),
        ),
        migrations.AlterField(
            model_name="facturaconfiguration",
            name="content_font",
            field=models.CharField(
                choices=[
                    ("Helvetica", "Helvetica"),
                    ("Times-Roman", "Times Roman"),
                    ("Courier", "Courier"),
                ],
                default="Helvetica Bold",
                help_text="Fuente para contenido",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="facturaconfiguration",
            name="header_font",
            field=models.CharField(
                choices=[
                    ("Helvetica", "Helvetica"),
                    ("Times-Roman", "Times Roman"),
                    ("Courier", "Courier"),
                ],
                default="Helvetica Bold",
                help_text="Fuente para encabezados",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="facturaconfiguration",
            name="margin_bottom",
            field=models.FloatField(default=0, help_text="Margen inferior en cm"),
        ),
        migrations.AlterField(
            model_name="facturaconfiguration",
            name="margin_left",
            field=models.FloatField(default=0.5, help_text="Margen izquierdo en cm"),
        ),
        migrations.AlterField(
            model_name="facturaconfiguration",
            name="margin_right",
            field=models.FloatField(default=0.5, help_text="Margen derecho en cm"),
        ),
        migrations.AlterField(
            model_name="facturaconfiguration",
            name="margin_top",
            field=models.FloatField(default=0, help_text="Margen superior en cm"),
        ),
    ]
