# Generated by Django 4.2.13 on 2024-05-30 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cliente", "0001_initial"),
        ("vendedor", "0001_initial"),
        ("articulo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_compra", models.DateField()),
                ("fecha_entrega", models.DateField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventas",
                        to="cliente.cliente",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventas",
                        to="vendedor.vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "venta",
                "verbose_name_plural": "ventas",
                "ordering": ["fecha_compra"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pagado", models.BooleanField(default=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Entregado", "Entregado"),
                            ("Listo para retirar", "Listo para retirar"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedido",
                        to="venta.venta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticuloVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveBigIntegerField(default=1)),
                ("precio", models.CharField(max_length=255)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articulos_vendidos",
                        to="articulo.articulo",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventas",
                        to="venta.venta",
                    ),
                ),
            ],
        ),
    ]
