# Generated by Django 5.0.3 on 2024-03-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('vendedor', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='vendedor.vendedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='cliente.cliente'),
        ),
    ]
