# Generated by Django 5.0.3 on 2024-04-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articuloventa',
            name='precio_minorista',
        ),
        migrations.AddField(
            model_name='articuloventa',
            name='vendido_por_mayor',
            field=models.BooleanField(default=False),
        ),
    ]
