# Generated by Django 5.0.3 on 2024-04-27 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_articulo_cantidad_por_mayor'),
        ('venta', '0002_remove_articuloventa_precio_minorista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloventa',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='articulo.articulo'),
        ),
        migrations.AlterField(
            model_name='articuloventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_vendidos', to='venta.venta'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('Listo para retirar', 'Listo para retirar')], default='Pendiente', max_length=20)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='venta.venta')),
            ],
        ),
    ]
