# Generated by Django 4.2.11 on 2024-04-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venta", "0002_remove_articuloventa_precio_minorista_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articuloventa",
            name="vendido_por_mayor",
        ),
        migrations.AddField(
            model_name="articuloventa",
            name="precio",
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="articuloventa",
            name="precio_minorista",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="articuloventa",
            name="cantidad",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
