# Generated by Django 5.0.3 on 2024-04-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_alter_articuloventa_articulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido',
            new_name='pagado',
        ),
    ]
