# Generated by Django 5.0.4 on 2024-05-05 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("venta", "0003_remove_articuloventa_vendido_por_mayor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articuloventa",
            name="precio_minorista",
        ),
    ]
