# Generated by Django 4.2 on 2024-05-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_remove_articuloventa_vendido_por_mayor_and_more'),
        ('venta', '0004_rename_pedido_pedido_pagado'),
    ]

    operations = [
    ]
