# Generated by Django 4.2.13 on 2024-05-11 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("venta", "0004_remove_articuloventa_precio_minorista"),
        ("venta", "0004_rename_pedido_pedido_pagado"),
    ]

    operations = []
