# Generated by Django 4.2.13 on 2024-05-14 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articulo", "0004_alter_articulo_precio_mayorista_and_more"),
        ("venta", "0005_merge_20240511_1603"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articuloventa",
            name="articulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articulos_ventdidos",
                to="articulo.articulo",
            ),
        ),
        migrations.AlterField(
            model_name="articuloventa",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ventas",
                to="venta.venta",
            ),
        ),
    ]
