# Generated by Django 4.2 on 2024-05-11 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0003_alter_articulo_cantidad_por_mayor_and_more'),
        ('venta', '0005_merge_20240510_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articuloventa',
            name='precio_minorista',
        ),
        migrations.AlterField(
            model_name='articuloventa',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_ventdidos', to='articulo.articulo'),
        ),
        migrations.AlterField(
            model_name='articuloventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='venta.venta'),
        ),
    ]
