client_config_backend: settings
client_config:
  access_type: offline
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.appdata