# Generated by Django 4.2.13 on 2024-06-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compra", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="direccion",
            field=models.CharField(default="direccion Vacia", max_length=255),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="telefono",
            field=models.CharField(default="0000000", max_length=20),
        ),
    ]
