# Generated by Django 5.0.3 on 2024-04-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compra", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="apellido",
            field=models.CharField(default="ordonez", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="cantidad",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
