# Generated by Django 5.0.3 on 2024-04-01 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articulo", "0001_initial"),
        ("compra", "0002_proveedor_apellido_alter_detallecompra_cantidad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="articulos",
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="articulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articulos_comprados",
                to="articulo.articulo",
            ),
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="compra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_compra",
                to="compra.compra",
            ),
        ),
    ]
