# Generated by Django 5.0.1 on 2024-01-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cliente", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="edad",
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
