# Generated by Django 4.2.13 on 2024-06-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendedor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendedor",
            name="apellido",
            field=models.TextField(default="Sin apellido"),
        ),
    ]
