# Generated by Django 4.2.13 on 2024-05-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveIntegerField()),
                (
                    "codigo_interno",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("stock", models.PositiveIntegerField()),
                (
                    "precio_minorista",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "precio_mayorista",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("vencimiento", models.DateField(blank=True)),
                (
                    "marca",
                    models.CharField(
                        blank=True, default="Generico", max_length=255, null=True
                    ),
                ),
                (
                    "cantidad_por_mayor",
                    models.PositiveIntegerField(default=100, null=True),
                ),
            ],
        ),
    ]
