# Generated by Django 4.2.11 on 2024-03-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.PositiveIntegerField()),
                (
                    "codigo_interno",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField()),
                (
                    "precio_minorista",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precio_mayorista",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("vencimiento", models.DateField(blank=True)),
                (
                    "marca",
                    models.CharField(
                        blank=True, default="Sin marca", max_length=255, null=True
                    ),
                ),
            ],
        ),
    ]
