# Generated by Django 5.0.3 on 2024-04-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cantidad_por_mayor',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
