# Generated by Django 5.0.4 on 2024-05-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articulo", "0002_articulo_cantidad_por_mayor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="cantidad_por_mayor",
            field=models.PositiveIntegerField(default=100, null=True),
        ),
    ]
