# Generated by Django 5.0.3 on 2024-03-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_articulo_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
