# Generated by Django 5.0.4 on 2024-05-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articulo", "0003_alter_articulo_cantidad_por_mayor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="precio_mayorista",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="precio_minorista",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
